/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BloqueadoRouteImport } from './routes/bloqueado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppAdminInvitacionesRouteImport } from './routes/_app/admin/invitaciones'
import { Route as AppEntrenarIndexRouteImport } from './routes/_app/entrenar/index'
import { Route as AppEntrenarActividadRouteImport } from './routes/_app/entrenar/actividad'
import { Route as AppEntrenarEjerciciosRouteImport } from './routes/_app/entrenar/ejercicios'
import { Route as AppEntrenarSesionRouteImport } from './routes/_app/entrenar/sesion'
import { Route as AppPerfilIndexRouteImport } from './routes/_app/perfil/index'
import { Route as AppPerfilCompromisoRouteImport } from './routes/_app/perfil/compromiso'
import { Route as AppPerfilVinculosRouteImport } from './routes/_app/perfil/vinculos'
import { Route as AppProgresoIndexRouteImport } from './routes/_app/progreso/index'
import { Route as AppProgresoCumplimientoRouteImport } from './routes/_app/progreso/cumplimiento'
import { Route as AppProgresoFotosRouteImport } from './routes/_app/progreso/fotos'
import { Route as AppProgresoMedidasRouteImport } from './routes/_app/progreso/medidas'
import { Route as AppProgresoRecordsRouteImport } from './routes/_app/progreso/records'
import { Route as AppProgresoResumenRouteImport } from './routes/_app/progreso/resumen'
import { Route as AppEntrenarHistorialSessionIdRouteImport } from './routes/_app/entrenar/historial.$sessionId'
import { Route as AppProgresoEjercicioExerciseIdRouteImport } from './routes/_app/progreso/ejercicio.$exerciseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueadoRoute = BloqueadoRouteImport.update({
  id: '/bloqueado',
  path: '/bloqueado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminInvitacionesRoute = AppAdminInvitacionesRouteImport.update({
  id: '/admin/invitaciones',
  path: '/admin/invitaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenarIndexRoute = AppEntrenarIndexRouteImport.update({
  id: '/entrenar/',
  path: '/entrenar/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenarActividadRoute = AppEntrenarActividadRouteImport.update({
  id: '/entrenar/actividad',
  path: '/entrenar/actividad',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenarEjerciciosRoute = AppEntrenarEjerciciosRouteImport.update({
  id: '/entrenar/ejercicios',
  path: '/entrenar/ejercicios',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenarSesionRoute = AppEntrenarSesionRouteImport.update({
  id: '/entrenar/sesion',
  path: '/entrenar/sesion',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilIndexRoute = AppPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilCompromisoRoute = AppPerfilCompromisoRouteImport.update({
  id: '/perfil/compromiso',
  path: '/perfil/compromiso',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilVinculosRoute = AppPerfilVinculosRouteImport.update({
  id: '/perfil/vinculos',
  path: '/perfil/vinculos',
  getParentRoute: () => AppRoute,
} as any)
const AppProgresoIndexRoute = AppProgresoIndexRouteImport.update({
  id: '/progreso/',
  path: '/progreso/',
  getParentRoute: () => AppRoute,
} as any)
const AppProgresoCumplimientoRoute = AppProgresoCumplimientoRouteImport.update({
  id: '/progreso/cumplimiento',
  path: '/progreso/cumplimiento',
  getParentRoute: () => AppRoute,
} as any)
const AppProgresoFotosRoute = AppProgresoFotosRouteImport.update({
  id: '/progreso/fotos',
  path: '/progreso/fotos',
  getParentRoute: () => AppRoute,
} as any)
const AppProgresoMedidasRoute = AppProgresoMedidasRouteImport.update({
  id: '/progreso/medidas',
  path: '/progreso/medidas',
  getParentRoute: () => AppRoute,
} as any)
const AppProgresoRecordsRoute = AppProgresoRecordsRouteImport.update({
  id: '/progreso/records',
  path: '/progreso/records',
  getParentRoute: () => AppRoute,
} as any)
const AppProgresoResumenRoute = AppProgresoResumenRouteImport.update({
  id: '/progreso/resumen',
  path: '/progreso/resumen',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenarHistorialSessionIdRoute =
  AppEntrenarHistorialSessionIdRouteImport.update({
    id: '/entrenar/historial/$sessionId',
    path: '/entrenar/historial/$sessionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProgresoEjercicioExerciseIdRoute =
  AppProgresoEjercicioExerciseIdRouteImport.update({
    id: '/progreso/ejercicio/$exerciseId',
    path: '/progreso/ejercicio/$exerciseId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/bloqueado': typeof BloqueadoRoute
  '/login': typeof LoginRoute
  '/plan': typeof AppPlanRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/invitaciones': typeof AppAdminInvitacionesRoute
  '/entrenar/actividad': typeof AppEntrenarActividadRoute
  '/entrenar/ejercicios': typeof AppEntrenarEjerciciosRoute
  '/entrenar/sesion': typeof AppEntrenarSesionRoute
  '/perfil/compromiso': typeof AppPerfilCompromisoRoute
  '/perfil/vinculos': typeof AppPerfilVinculosRoute
  '/progreso/cumplimiento': typeof AppProgresoCumplimientoRoute
  '/progreso/fotos': typeof AppProgresoFotosRoute
  '/progreso/medidas': typeof AppProgresoMedidasRoute
  '/progreso/records': typeof AppProgresoRecordsRoute
  '/progreso/resumen': typeof AppProgresoResumenRoute
  '/entrenar/': typeof AppEntrenarIndexRoute
  '/perfil/': typeof AppPerfilIndexRoute
  '/progreso/': typeof AppProgresoIndexRoute
  '/entrenar/historial/$sessionId': typeof AppEntrenarHistorialSessionIdRoute
  '/progreso/ejercicio/$exerciseId': typeof AppProgresoEjercicioExerciseIdRoute
}
export interface FileRoutesByTo {
  '/bloqueado': typeof BloqueadoRoute
  '/login': typeof LoginRoute
  '/plan': typeof AppPlanRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
  '/admin/invitaciones': typeof AppAdminInvitacionesRoute
  '/entrenar/actividad': typeof AppEntrenarActividadRoute
  '/entrenar/ejercicios': typeof AppEntrenarEjerciciosRoute
  '/entrenar/sesion': typeof AppEntrenarSesionRoute
  '/perfil/compromiso': typeof AppPerfilCompromisoRoute
  '/perfil/vinculos': typeof AppPerfilVinculosRoute
  '/progreso/cumplimiento': typeof AppProgresoCumplimientoRoute
  '/progreso/fotos': typeof AppProgresoFotosRoute
  '/progreso/medidas': typeof AppProgresoMedidasRoute
  '/progreso/records': typeof AppProgresoRecordsRoute
  '/progreso/resumen': typeof AppProgresoResumenRoute
  '/entrenar': typeof AppEntrenarIndexRoute
  '/perfil': typeof AppPerfilIndexRoute
  '/progreso': typeof AppProgresoIndexRoute
  '/entrenar/historial/$sessionId': typeof AppEntrenarHistorialSessionIdRoute
  '/progreso/ejercicio/$exerciseId': typeof AppProgresoEjercicioExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/bloqueado': typeof BloqueadoRoute
  '/login': typeof LoginRoute
  '/_app/plan': typeof AppPlanRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/invitaciones': typeof AppAdminInvitacionesRoute
  '/_app/entrenar/actividad': typeof AppEntrenarActividadRoute
  '/_app/entrenar/ejercicios': typeof AppEntrenarEjerciciosRoute
  '/_app/entrenar/sesion': typeof AppEntrenarSesionRoute
  '/_app/perfil/compromiso': typeof AppPerfilCompromisoRoute
  '/_app/perfil/vinculos': typeof AppPerfilVinculosRoute
  '/_app/progreso/cumplimiento': typeof AppProgresoCumplimientoRoute
  '/_app/progreso/fotos': typeof AppProgresoFotosRoute
  '/_app/progreso/medidas': typeof AppProgresoMedidasRoute
  '/_app/progreso/records': typeof AppProgresoRecordsRoute
  '/_app/progreso/resumen': typeof AppProgresoResumenRoute
  '/_app/entrenar/': typeof AppEntrenarIndexRoute
  '/_app/perfil/': typeof AppPerfilIndexRoute
  '/_app/progreso/': typeof AppProgresoIndexRoute
  '/_app/entrenar/historial/$sessionId': typeof AppEntrenarHistorialSessionIdRoute
  '/_app/progreso/ejercicio/$exerciseId': typeof AppProgresoEjercicioExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bloqueado'
    | '/login'
    | '/plan'
    | '/api/health'
    | '/auth/callback'
    | '/admin/invitaciones'
    | '/entrenar/actividad'
    | '/entrenar/ejercicios'
    | '/entrenar/sesion'
    | '/perfil/compromiso'
    | '/perfil/vinculos'
    | '/progreso/cumplimiento'
    | '/progreso/fotos'
    | '/progreso/medidas'
    | '/progreso/records'
    | '/progreso/resumen'
    | '/entrenar/'
    | '/perfil/'
    | '/progreso/'
    | '/entrenar/historial/$sessionId'
    | '/progreso/ejercicio/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bloqueado'
    | '/login'
    | '/plan'
    | '/api/health'
    | '/auth/callback'
    | '/'
    | '/admin/invitaciones'
    | '/entrenar/actividad'
    | '/entrenar/ejercicios'
    | '/entrenar/sesion'
    | '/perfil/compromiso'
    | '/perfil/vinculos'
    | '/progreso/cumplimiento'
    | '/progreso/fotos'
    | '/progreso/medidas'
    | '/progreso/records'
    | '/progreso/resumen'
    | '/entrenar'
    | '/perfil'
    | '/progreso'
    | '/entrenar/historial/$sessionId'
    | '/progreso/ejercicio/$exerciseId'
  id:
    | '__root__'
    | '/_app'
    | '/bloqueado'
    | '/login'
    | '/_app/plan'
    | '/api/health'
    | '/auth/callback'
    | '/_app/'
    | '/_app/admin/invitaciones'
    | '/_app/entrenar/actividad'
    | '/_app/entrenar/ejercicios'
    | '/_app/entrenar/sesion'
    | '/_app/perfil/compromiso'
    | '/_app/perfil/vinculos'
    | '/_app/progreso/cumplimiento'
    | '/_app/progreso/fotos'
    | '/_app/progreso/medidas'
    | '/_app/progreso/records'
    | '/_app/progreso/resumen'
    | '/_app/entrenar/'
    | '/_app/perfil/'
    | '/_app/progreso/'
    | '/_app/entrenar/historial/$sessionId'
    | '/_app/progreso/ejercicio/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  BloqueadoRoute: typeof BloqueadoRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueado': {
      id: '/bloqueado'
      path: '/bloqueado'
      fullPath: '/bloqueado'
      preLoaderRoute: typeof BloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/invitaciones': {
      id: '/_app/admin/invitaciones'
      path: '/admin/invitaciones'
      fullPath: '/admin/invitaciones'
      preLoaderRoute: typeof AppAdminInvitacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entrenar/': {
      id: '/_app/entrenar/'
      path: '/entrenar'
      fullPath: '/entrenar/'
      preLoaderRoute: typeof AppEntrenarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entrenar/actividad': {
      id: '/_app/entrenar/actividad'
      path: '/entrenar/actividad'
      fullPath: '/entrenar/actividad'
      preLoaderRoute: typeof AppEntrenarActividadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entrenar/ejercicios': {
      id: '/_app/entrenar/ejercicios'
      path: '/entrenar/ejercicios'
      fullPath: '/entrenar/ejercicios'
      preLoaderRoute: typeof AppEntrenarEjerciciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entrenar/sesion': {
      id: '/_app/entrenar/sesion'
      path: '/entrenar/sesion'
      fullPath: '/entrenar/sesion'
      preLoaderRoute: typeof AppEntrenarSesionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/': {
      id: '/_app/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AppPerfilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/compromiso': {
      id: '/_app/perfil/compromiso'
      path: '/perfil/compromiso'
      fullPath: '/perfil/compromiso'
      preLoaderRoute: typeof AppPerfilCompromisoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/vinculos': {
      id: '/_app/perfil/vinculos'
      path: '/perfil/vinculos'
      fullPath: '/perfil/vinculos'
      preLoaderRoute: typeof AppPerfilVinculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progreso/': {
      id: '/_app/progreso/'
      path: '/progreso'
      fullPath: '/progreso/'
      preLoaderRoute: typeof AppProgresoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progreso/cumplimiento': {
      id: '/_app/progreso/cumplimiento'
      path: '/progreso/cumplimiento'
      fullPath: '/progreso/cumplimiento'
      preLoaderRoute: typeof AppProgresoCumplimientoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progreso/fotos': {
      id: '/_app/progreso/fotos'
      path: '/progreso/fotos'
      fullPath: '/progreso/fotos'
      preLoaderRoute: typeof AppProgresoFotosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progreso/medidas': {
      id: '/_app/progreso/medidas'
      path: '/progreso/medidas'
      fullPath: '/progreso/medidas'
      preLoaderRoute: typeof AppProgresoMedidasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progreso/records': {
      id: '/_app/progreso/records'
      path: '/progreso/records'
      fullPath: '/progreso/records'
      preLoaderRoute: typeof AppProgresoRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progreso/resumen': {
      id: '/_app/progreso/resumen'
      path: '/progreso/resumen'
      fullPath: '/progreso/resumen'
      preLoaderRoute: typeof AppProgresoResumenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entrenar/historial/$sessionId': {
      id: '/_app/entrenar/historial/$sessionId'
      path: '/entrenar/historial/$sessionId'
      fullPath: '/entrenar/historial/$sessionId'
      preLoaderRoute: typeof AppEntrenarHistorialSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progreso/ejercicio/$exerciseId': {
      id: '/_app/progreso/ejercicio/$exerciseId'
      path: '/progreso/ejercicio/$exerciseId'
      fullPath: '/progreso/ejercicio/$exerciseId'
      preLoaderRoute: typeof AppProgresoEjercicioExerciseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPlanRoute: typeof AppPlanRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminInvitacionesRoute: typeof AppAdminInvitacionesRoute
  AppEntrenarActividadRoute: typeof AppEntrenarActividadRoute
  AppEntrenarEjerciciosRoute: typeof AppEntrenarEjerciciosRoute
  AppEntrenarSesionRoute: typeof AppEntrenarSesionRoute
  AppPerfilCompromisoRoute: typeof AppPerfilCompromisoRoute
  AppPerfilVinculosRoute: typeof AppPerfilVinculosRoute
  AppProgresoCumplimientoRoute: typeof AppProgresoCumplimientoRoute
  AppProgresoFotosRoute: typeof AppProgresoFotosRoute
  AppProgresoMedidasRoute: typeof AppProgresoMedidasRoute
  AppProgresoRecordsRoute: typeof AppProgresoRecordsRoute
  AppProgresoResumenRoute: typeof AppProgresoResumenRoute
  AppEntrenarIndexRoute: typeof AppEntrenarIndexRoute
  AppPerfilIndexRoute: typeof AppPerfilIndexRoute
  AppProgresoIndexRoute: typeof AppProgresoIndexRoute
  AppEntrenarHistorialSessionIdRoute: typeof AppEntrenarHistorialSessionIdRoute
  AppProgresoEjercicioExerciseIdRoute: typeof AppProgresoEjercicioExerciseIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPlanRoute: AppPlanRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminInvitacionesRoute: AppAdminInvitacionesRoute,
  AppEntrenarActividadRoute: AppEntrenarActividadRoute,
  AppEntrenarEjerciciosRoute: AppEntrenarEjerciciosRoute,
  AppEntrenarSesionRoute: AppEntrenarSesionRoute,
  AppPerfilCompromisoRoute: AppPerfilCompromisoRoute,
  AppPerfilVinculosRoute: AppPerfilVinculosRoute,
  AppProgresoCumplimientoRoute: AppProgresoCumplimientoRoute,
  AppProgresoFotosRoute: AppProgresoFotosRoute,
  AppProgresoMedidasRoute: AppProgresoMedidasRoute,
  AppProgresoRecordsRoute: AppProgresoRecordsRoute,
  AppProgresoResumenRoute: AppProgresoResumenRoute,
  AppEntrenarIndexRoute: AppEntrenarIndexRoute,
  AppPerfilIndexRoute: AppPerfilIndexRoute,
  AppProgresoIndexRoute: AppProgresoIndexRoute,
  AppEntrenarHistorialSessionIdRoute: AppEntrenarHistorialSessionIdRoute,
  AppProgresoEjercicioExerciseIdRoute: AppProgresoEjercicioExerciseIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  BloqueadoRoute: BloqueadoRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
