/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BloqueadoRouteImport } from './routes/bloqueado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppEntrenarRouteImport } from './routes/_app/entrenar'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppProgresoRouteImport } from './routes/_app/progreso'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppAdminInvitacionesRouteImport } from './routes/_app/admin/invitaciones'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueadoRoute = BloqueadoRouteImport.update({
  id: '/bloqueado',
  path: '/bloqueado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenarRoute = AppEntrenarRouteImport.update({
  id: '/entrenar',
  path: '/entrenar',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppProgresoRoute = AppProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminInvitacionesRoute = AppAdminInvitacionesRouteImport.update({
  id: '/admin/invitaciones',
  path: '/admin/invitaciones',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/bloqueado': typeof BloqueadoRoute
  '/login': typeof LoginRoute
  '/entrenar': typeof AppEntrenarRoute
  '/perfil': typeof AppPerfilRoute
  '/plan': typeof AppPlanRoute
  '/progreso': typeof AppProgresoRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/invitaciones': typeof AppAdminInvitacionesRoute
}
export interface FileRoutesByTo {
  '/bloqueado': typeof BloqueadoRoute
  '/login': typeof LoginRoute
  '/entrenar': typeof AppEntrenarRoute
  '/perfil': typeof AppPerfilRoute
  '/plan': typeof AppPlanRoute
  '/progreso': typeof AppProgresoRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
  '/admin/invitaciones': typeof AppAdminInvitacionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/bloqueado': typeof BloqueadoRoute
  '/login': typeof LoginRoute
  '/_app/entrenar': typeof AppEntrenarRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/progreso': typeof AppProgresoRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/invitaciones': typeof AppAdminInvitacionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bloqueado'
    | '/login'
    | '/entrenar'
    | '/perfil'
    | '/plan'
    | '/progreso'
    | '/api/health'
    | '/auth/callback'
    | '/admin/invitaciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bloqueado'
    | '/login'
    | '/entrenar'
    | '/perfil'
    | '/plan'
    | '/progreso'
    | '/api/health'
    | '/auth/callback'
    | '/'
    | '/admin/invitaciones'
  id:
    | '__root__'
    | '/_app'
    | '/bloqueado'
    | '/login'
    | '/_app/entrenar'
    | '/_app/perfil'
    | '/_app/plan'
    | '/_app/progreso'
    | '/api/health'
    | '/auth/callback'
    | '/_app/'
    | '/_app/admin/invitaciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  BloqueadoRoute: typeof BloqueadoRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueado': {
      id: '/bloqueado'
      path: '/bloqueado'
      fullPath: '/bloqueado'
      preLoaderRoute: typeof BloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entrenar': {
      id: '/_app/entrenar'
      path: '/entrenar'
      fullPath: '/entrenar'
      preLoaderRoute: typeof AppEntrenarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progreso': {
      id: '/_app/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AppProgresoRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/invitaciones': {
      id: '/_app/admin/invitaciones'
      path: '/admin/invitaciones'
      fullPath: '/admin/invitaciones'
      preLoaderRoute: typeof AppAdminInvitacionesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEntrenarRoute: typeof AppEntrenarRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProgresoRoute: typeof AppProgresoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminInvitacionesRoute: typeof AppAdminInvitacionesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEntrenarRoute: AppEntrenarRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanRoute: AppPlanRoute,
  AppProgresoRoute: AppProgresoRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminInvitacionesRoute: AppAdminInvitacionesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  BloqueadoRoute: BloqueadoRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
