-- 0006_seed_exercises_strength.sql
-- Semilla: ejercicios de fuerza (CLAUDE.md §6). Requiere 0005.
-- GENERADO por scripts/seed-sql.ts a partir de supabase/seed/*.json. No editar a mano.
-- Idempotente: se puede ejecutar varias veces.

insert into public.exercises (
  id, name, aliases, category, tracking_type, equipment, is_unilateral, is_compound,
  default_rest_s, technique_notes
) values
  ('back_squat', 'Sentadilla con barra', array['back squat', 'sentadilla trasera', 'squat']::text[], 'strength', 'weight_reps', array['barbell', 'rack']::text[], false, true, 180, 'Pies a la anchura de hombros, rodillas en la línea de los pies, espalda neutra y bajar al menos hasta paralelo.'),
  ('goblet_squat', 'Sentadilla goblet', array['goblet squat', 'sentadilla copa']::text[], 'strength', 'weight_reps', array['dumbbell', 'kettlebell']::text[], false, true, 120, 'Peso pegado al pecho, codos entre las rodillas y torso erguido.'),
  ('leg_press', 'Prensa', array['leg press', 'prensa de piernas']::text[], 'strength', 'weight_reps', array['machine']::text[], false, true, 150, 'Zona lumbar apoyada en el respaldo; no bloquear las rodillas arriba.'),
  ('deadlift', 'Peso muerto', array['deadlift', 'peso muerto convencional']::text[], 'strength', 'weight_reps', array['barbell']::text[], false, true, 180, 'Barra pegada a las piernas, espalda neutra y empujar el suelo con las piernas.'),
  ('romanian_deadlift', 'Peso muerto rumano', array['romanian deadlift', 'rdl', 'peso muerto piernas semirrígidas']::text[], 'strength', 'weight_reps', array['barbell', 'dumbbell']::text[], false, true, 150, 'Cadera atrás con rodillas ligeramente flexionadas, hasta notar tensión en isquios.'),
  ('hip_thrust', 'Hip thrust', array['empuje de cadera', 'puente de glúteo con barra']::text[], 'strength', 'weight_reps', array['barbell', 'bench']::text[], false, true, 120, 'Escápulas en el banco, barbilla recogida y extensión completa de cadera arriba.'),
  ('lunge', 'Zancadas', array['lunges', 'zancada', 'estocadas']::text[], 'strength', 'weight_reps', array['dumbbell', 'barbell', 'bodyweight']::text[], true, true, 120, 'Paso largo, rodilla trasera cerca del suelo y torso erguido.'),
  ('bulgarian_split_squat', 'Sentadilla búlgara', array['búlgara', 'bulgarian split squat', 'split squat']::text[], 'strength', 'weight_reps', array['dumbbell', 'bench']::text[], true, true, 120, 'Pie trasero en el banco; bajar en vertical con la rodilla delantera estable.'),
  ('leg_curl', 'Curl femoral', array['leg curl', 'curl de isquios', 'femoral tumbado', 'femoral sentado']::text[], 'strength', 'weight_reps', array['machine']::text[], false, false, 90, 'Controlar la bajada y no despegar la cadera.'),
  ('leg_extension', 'Extensión de cuádriceps', array['leg extension', 'extensiones de cuádriceps']::text[], 'strength', 'weight_reps', array['machine']::text[], false, false, 90, 'Rodilla alineada con el eje de la máquina; pausa breve arriba.'),
  ('calf_raise', 'Elevación de gemelos', array['calf raise', 'gemelos de pie', 'gemelos sentado']::text[], 'strength', 'weight_reps', array['machine', 'dumbbell', 'bodyweight']::text[], false, false, 60, 'Recorrido completo con pausa abajo y arriba.'),
  ('bench_press', 'Press banca', array['bench press', 'press de banca', 'press plano']::text[], 'strength', 'weight_reps', array['barbell', 'bench', 'rack']::text[], false, true, 180, 'Escápulas retraídas, pies firmes, barra al pecho medio y codos a unos 45°.'),
  ('incline_db_press', 'Press inclinado con mancuernas', array['incline dumbbell press', 'press inclinado mancuernas']::text[], 'strength', 'weight_reps', array['dumbbell', 'bench']::text[], false, true, 120, 'Banco a 30-45°; bajar controlado hasta la altura del pecho.'),
  ('dips', 'Fondos', array['dips', 'fondos en paralelas']::text[], 'strength', 'reps', array['dip_bars', 'bodyweight']::text[], false, true, 120, 'Torso ligeramente inclinado; bajar hasta unos 90° de codo.'),
  ('push_up', 'Flexiones', array['push up', 'push-ups', 'flexiones de brazos']::text[], 'strength', 'reps', array['bodyweight']::text[], false, true, 90, 'Cuerpo en bloque, codos a unos 45° y pecho casi al suelo.'),
  ('overhead_press', 'Press militar', array['overhead press', 'ohp', 'press de hombros', 'military press']::text[], 'strength', 'weight_reps', array['barbell', 'dumbbell']::text[], false, true, 150, 'Glúteos y abdomen apretados; la barra sube en línea recta sobre la cabeza.'),
  ('lateral_raise', 'Elevaciones laterales', array['lateral raise', 'elevaciones laterales con mancuernas']::text[], 'strength', 'weight_reps', array['dumbbell', 'cable']::text[], false, false, 60, 'Codos ligeramente flexionados; subir hasta la altura de los hombros sin impulso.'),
  ('face_pull', 'Face pull', array['tirón a la cara', 'facepull']::text[], 'strength', 'weight_reps', array['cable', 'band']::text[], false, false, 60, 'Tirar de la cuerda hacia la frente separando las manos y rotando hacia fuera.'),
  ('pull_up', 'Dominadas', array['pull up', 'chin up', 'dominadas prono', 'dominadas supino']::text[], 'strength', 'reps', array['pullup_bar', 'bodyweight']::text[], false, true, 150, 'Desde brazos extendidos, llevar el pecho hacia la barra sin balanceo.'),
  ('lat_pulldown', 'Jalón al pecho', array['lat pulldown', 'jalón', 'polea al pecho']::text[], 'strength', 'weight_reps', array['cable', 'machine']::text[], false, true, 120, 'Tirar con los codos hacia abajo y atrás, pecho alto.'),
  ('barbell_row', 'Remo con barra', array['barbell row', 'remo inclinado', 'bent over row']::text[], 'strength', 'weight_reps', array['barbell']::text[], false, true, 150, 'Torso inclinado y espalda neutra; llevar la barra al abdomen.'),
  ('db_row', 'Remo con mancuerna', array['dumbbell row', 'remo a una mano']::text[], 'strength', 'weight_reps', array['dumbbell', 'bench']::text[], true, true, 90, 'Apoyo en banco, espalda plana; llevar el codo hacia la cadera.'),
  ('biceps_curl', 'Curl de bíceps', array['biceps curl', 'curl con barra', 'curl con mancuernas']::text[], 'strength', 'weight_reps', array['dumbbell', 'barbell', 'cable']::text[], false, false, 60, 'Codos pegados al cuerpo; sin balancear el torso.'),
  ('triceps_pushdown', 'Extensión de tríceps en polea', array['triceps pushdown', 'jalón de tríceps', 'tríceps en polea']::text[], 'strength', 'weight_reps', array['cable']::text[], false, false, 60, 'Codos fijos junto al cuerpo; extensión completa abajo.'),
  ('plank', 'Plancha', array['plank', 'plancha abdominal']::text[], 'strength', 'time', array['bodyweight']::text[], false, false, 60, 'Cuerpo en línea recta, glúteos y abdomen activos, sin hundir la cadera.'),
  ('ab_wheel', 'Rueda abdominal', array['ab wheel', 'rueda de abdominales', 'ab roller']::text[], 'strength', 'reps', array['ab_wheel']::text[], false, false, 60, 'Avanzar solo hasta donde puedas mantener la zona lumbar neutra.'),
  ('pallof_press', 'Pallof press', array['press pallof', 'antirrotación']::text[], 'strength', 'reps', array['cable', 'band']::text[], true, false, 60, 'De lado a la polea; extender los brazos sin dejar que el tronco rote.')
on conflict (id) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  category = excluded.category,
  tracking_type = excluded.tracking_type,
  equipment = excluded.equipment,
  is_unilateral = excluded.is_unilateral,
  is_compound = excluded.is_compound,
  default_rest_s = excluded.default_rest_s,
  technique_notes = excluded.technique_notes
where public.exercises.owner_id is null;

-- Músculos: se reescriben para que la semilla sea la fuente de verdad.
delete from public.exercise_muscles where exercise_id in ('back_squat', 'goblet_squat', 'leg_press', 'deadlift', 'romanian_deadlift', 'hip_thrust', 'lunge', 'bulgarian_split_squat', 'leg_curl', 'leg_extension', 'calf_raise', 'bench_press', 'incline_db_press', 'dips', 'push_up', 'overhead_press', 'lateral_raise', 'face_pull', 'pull_up', 'lat_pulldown', 'barbell_row', 'db_row', 'biceps_curl', 'triceps_pushdown', 'plank', 'ab_wheel', 'pallof_press');

insert into public.exercise_muscles (exercise_id, muscle_id, role) values
  ('back_squat', 'quads', 'primary'),
  ('back_squat', 'glutes', 'primary'),
  ('back_squat', 'adductors', 'secondary'),
  ('back_squat', 'core', 'secondary'),
  ('back_squat', 'lower_back', 'secondary'),
  ('goblet_squat', 'quads', 'primary'),
  ('goblet_squat', 'glutes', 'primary'),
  ('goblet_squat', 'core', 'secondary'),
  ('leg_press', 'quads', 'primary'),
  ('leg_press', 'glutes', 'primary'),
  ('leg_press', 'adductors', 'secondary'),
  ('deadlift', 'hamstrings', 'primary'),
  ('deadlift', 'glutes', 'primary'),
  ('deadlift', 'lower_back', 'primary'),
  ('deadlift', 'upper_back', 'secondary'),
  ('deadlift', 'forearms', 'secondary'),
  ('deadlift', 'core', 'secondary'),
  ('romanian_deadlift', 'hamstrings', 'primary'),
  ('romanian_deadlift', 'glutes', 'primary'),
  ('romanian_deadlift', 'lower_back', 'secondary'),
  ('hip_thrust', 'glutes', 'primary'),
  ('hip_thrust', 'hamstrings', 'secondary'),
  ('lunge', 'quads', 'primary'),
  ('lunge', 'glutes', 'primary'),
  ('lunge', 'adductors', 'secondary'),
  ('lunge', 'core', 'secondary'),
  ('bulgarian_split_squat', 'quads', 'primary'),
  ('bulgarian_split_squat', 'glutes', 'primary'),
  ('bulgarian_split_squat', 'adductors', 'secondary'),
  ('leg_curl', 'hamstrings', 'primary'),
  ('leg_extension', 'quads', 'primary'),
  ('calf_raise', 'calves', 'primary'),
  ('bench_press', 'chest', 'primary'),
  ('bench_press', 'triceps', 'secondary'),
  ('bench_press', 'delt_front', 'secondary'),
  ('incline_db_press', 'chest', 'primary'),
  ('incline_db_press', 'delt_front', 'primary'),
  ('incline_db_press', 'triceps', 'secondary'),
  ('dips', 'chest', 'primary'),
  ('dips', 'triceps', 'primary'),
  ('dips', 'delt_front', 'secondary'),
  ('push_up', 'chest', 'primary'),
  ('push_up', 'triceps', 'secondary'),
  ('push_up', 'delt_front', 'secondary'),
  ('push_up', 'core', 'secondary'),
  ('overhead_press', 'delt_front', 'primary'),
  ('overhead_press', 'delt_side', 'primary'),
  ('overhead_press', 'triceps', 'secondary'),
  ('overhead_press', 'core', 'secondary'),
  ('lateral_raise', 'delt_side', 'primary'),
  ('face_pull', 'delt_rear', 'primary'),
  ('face_pull', 'upper_back', 'primary'),
  ('pull_up', 'lats', 'primary'),
  ('pull_up', 'biceps', 'secondary'),
  ('pull_up', 'upper_back', 'secondary'),
  ('pull_up', 'forearms', 'secondary'),
  ('lat_pulldown', 'lats', 'primary'),
  ('lat_pulldown', 'biceps', 'secondary'),
  ('lat_pulldown', 'upper_back', 'secondary'),
  ('barbell_row', 'upper_back', 'primary'),
  ('barbell_row', 'lats', 'primary'),
  ('barbell_row', 'delt_rear', 'secondary'),
  ('barbell_row', 'biceps', 'secondary'),
  ('barbell_row', 'lower_back', 'secondary'),
  ('db_row', 'lats', 'primary'),
  ('db_row', 'upper_back', 'primary'),
  ('db_row', 'biceps', 'secondary'),
  ('db_row', 'delt_rear', 'secondary'),
  ('biceps_curl', 'biceps', 'primary'),
  ('biceps_curl', 'forearms', 'secondary'),
  ('triceps_pushdown', 'triceps', 'primary'),
  ('plank', 'core', 'primary'),
  ('ab_wheel', 'core', 'primary'),
  ('pallof_press', 'core', 'primary')
on conflict (exercise_id, muscle_id) do update set role = excluded.role;
