-- 0007_seed_exercises_functional_cardio.sql
-- Semilla: ejercicios functional/Hyrox/Deka, cardio y deportes (CLAUDE.md §6). Requiere 0005.
-- GENERADO por scripts/seed-sql.ts a partir de supabase/seed/*.json. No editar a mano.
-- Idempotente: se puede ejecutar varias veces.

insert into public.exercises (
  id, name, aliases, category, tracking_type, equipment, is_unilateral, is_compound,
  default_rest_s, technique_notes
) values
  ('kettlebell_swing', 'Kettlebell swing', array['swing con kettlebell', 'kb swing', 'balanceo con pesa rusa']::text[], 'functional', 'weight_reps', array['kettlebell']::text[], false, true, 90, 'Bisagra de cadera explosiva; los brazos solo guían la pesa.'),
  ('thruster', 'Thruster', array['sentadilla con press']::text[], 'functional', 'weight_reps', array['barbell', 'dumbbell']::text[], false, true, 120, 'Sentadilla frontal y press encadenados en un solo movimiento.'),
  ('wall_ball', 'Wall ball', array['wall balls', 'lanzamiento a la pared']::text[], 'functional', 'weight_reps', array['medball']::text[], false, true, 90, 'Sentadilla completa y lanzamiento al objetivo aprovechando el impulso de piernas.'),
  ('burpee', 'Burpee', array['burpees']::text[], 'functional', 'reps', array['bodyweight']::text[], false, true, 60, 'Pecho al suelo, levantarse y saltar con extensión completa.'),
  ('burpee_broad_jump', 'Burpee broad jump', array['burpee con salto horizontal', 'bbj']::text[], 'functional', 'distance_time', array['bodyweight']::text[], false, true, 90, 'Burpee y salto hacia delante con los dos pies; aterrizar suave.'),
  ('box_jump', 'Box jump', array['salto al cajón']::text[], 'functional', 'reps', array['box']::text[], false, true, 90, 'Aterrizar con todo el pie sobre el cajón y extender la cadera arriba; bajar andando.'),
  ('box_jump_over', 'Box jump over', array['salto por encima del cajón', 'bjo']::text[], 'functional', 'reps', array['box']::text[], false, true, 90, 'Saltar o subir al cajón y pasar al otro lado.'),
  ('sled_push', 'Sled push', array['empuje de trineo', 'trineo empuje']::text[], 'functional', 'distance_time', array['sled']::text[], false, true, 120, 'Brazos extendidos o semiflexionados, cuerpo inclinado y pasos cortos y potentes.'),
  ('sled_pull', 'Sled pull', array['arrastre de trineo', 'trineo tirón']::text[], 'functional', 'distance_time', array['sled']::text[], false, true, 120, 'Tirar de la cuerda mano a mano con la cadera baja y la espalda neutra.'),
  ('farmers_carry', 'Farmers carry', array['paseo del granjero', 'farmer walk']::text[], 'functional', 'distance_time', array['kettlebell', 'dumbbell']::text[], false, true, 90, 'Hombros atrás, tronco firme y pasos rápidos y cortos.'),
  ('sandbag_lunge', 'Sandbag lunges', array['zancadas con saco', 'sandbag lunge']::text[], 'functional', 'distance_time', array['sandbag']::text[], true, true, 90, 'Saco sobre los hombros; rodilla trasera cerca del suelo en cada paso.'),
  ('med_ball_situp_throw', 'Med ball sit-up throw', array['abdominal con lanzamiento de balón']::text[], 'functional', 'reps', array['medball']::text[], false, false, 60, 'Subir con el balón sobre la cabeza y lanzarlo al llegar arriba.'),
  ('dead_ball_over', 'Dead ball over', array['lanzamiento de dead ball por encima del hombro', 'ball over shoulder']::text[], 'functional', 'weight_reps', array['deadball']::text[], false, true, 90, 'Recoger la bola con la espalda neutra y pasarla por encima del hombro o la valla.'),
  ('skierg', 'SkiErg', array['ski erg', 'esquí ergómetro']::text[], 'functional', 'distance_time', array['skierg']::text[], false, true, 120, 'Tirón desde arriba con cadera y core; brazos casi extendidos.'),
  ('row_erg', 'Remo ergómetro', array['rowing', 'remo', 'concept2', 'row']::text[], 'functional', 'distance_time', array['rower']::text[], false, true, 120, 'Orden: piernas, tronco y brazos; al volver, al revés.'),
  ('air_bike', 'Assault / air bike', array['assault bike', 'air bike', 'echo bike', 'bici de aire']::text[], 'functional', 'calories', array['air_bike']::text[], false, true, 120, 'Empujar y tirar con brazos y piernas a la vez.'),
  ('double_unders', 'Double unders / comba', array['comba', 'saltar a la comba', 'double unders', 'jump rope']::text[], 'functional', 'reps', array['jump_rope']::text[], false, false, 60, 'Saltos bajos sobre las puntas; el giro sale de las muñecas.'),
  ('run', 'Carrera', array['correr', 'running', 'rodaje', 'trote']::text[], 'cardio', 'distance_time', '{}'::text[], false, true, 90, null),
  ('swim_freestyle', 'Natación: crol', array['crol', 'freestyle', 'nadar']::text[], 'cardio', 'distance_time', array['pool']::text[], false, true, 30, null),
  ('swim_backstroke', 'Natación: espalda', array['espalda', 'backstroke']::text[], 'cardio', 'distance_time', array['pool']::text[], false, true, 30, null),
  ('swim_breaststroke', 'Natación: braza', array['braza', 'breaststroke']::text[], 'cardio', 'distance_time', array['pool']::text[], false, true, 30, null),
  ('swim_drills', 'Natación: técnica', array['técnica de natación', 'drills', 'ejercicios de técnica']::text[], 'cardio', 'distance_time', array['pool']::text[], false, true, 30, null),
  ('bike', 'Bici', array['ciclismo', 'bicicleta', 'cycling']::text[], 'cardio', 'distance_time', array['bike']::text[], false, true, 90, null),
  ('spinning', 'Spinning', array['bici estática', 'indoor cycling', 'ciclo indoor']::text[], 'cardio', 'distance_time', array['bike']::text[], false, true, 60, null),
  ('yoga', 'Yoga', '{}'::text[], 'mobility', 'duration_only', array['mat']::text[], false, false, 0, null),
  ('fronton', 'Frontón', array['pelota', 'pala', 'frontenis']::text[], 'sport', 'duration_only', '{}'::text[], false, false, 0, null),
  ('surf', 'Surf', '{}'::text[], 'sport', 'duration_only', array['board']::text[], false, false, 0, null),
  ('other_activity', 'Otra actividad', array['otro', 'deporte']::text[], 'sport', 'duration_only', '{}'::text[], false, false, 0, null)
on conflict (id) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  category = excluded.category,
  tracking_type = excluded.tracking_type,
  equipment = excluded.equipment,
  is_unilateral = excluded.is_unilateral,
  is_compound = excluded.is_compound,
  default_rest_s = excluded.default_rest_s,
  technique_notes = excluded.technique_notes
where public.exercises.owner_id is null;

-- Músculos: se reescriben para que la semilla sea la fuente de verdad.
delete from public.exercise_muscles where exercise_id in ('kettlebell_swing', 'thruster', 'wall_ball', 'burpee', 'burpee_broad_jump', 'box_jump', 'box_jump_over', 'sled_push', 'sled_pull', 'farmers_carry', 'sandbag_lunge', 'med_ball_situp_throw', 'dead_ball_over', 'skierg', 'row_erg', 'air_bike', 'double_unders', 'run', 'swim_freestyle', 'swim_backstroke', 'swim_breaststroke', 'swim_drills', 'bike', 'spinning', 'yoga', 'fronton', 'surf', 'other_activity');

insert into public.exercise_muscles (exercise_id, muscle_id, role) values
  ('kettlebell_swing', 'glutes', 'primary'),
  ('kettlebell_swing', 'hamstrings', 'primary'),
  ('kettlebell_swing', 'lower_back', 'secondary'),
  ('kettlebell_swing', 'core', 'secondary'),
  ('kettlebell_swing', 'forearms', 'secondary'),
  ('thruster', 'quads', 'primary'),
  ('thruster', 'glutes', 'primary'),
  ('thruster', 'delt_front', 'primary'),
  ('thruster', 'triceps', 'secondary'),
  ('thruster', 'core', 'secondary'),
  ('wall_ball', 'quads', 'primary'),
  ('wall_ball', 'glutes', 'primary'),
  ('wall_ball', 'delt_front', 'primary'),
  ('wall_ball', 'core', 'secondary'),
  ('wall_ball', 'triceps', 'secondary'),
  ('burpee', 'chest', 'primary'),
  ('burpee', 'quads', 'primary'),
  ('burpee', 'core', 'secondary'),
  ('burpee', 'triceps', 'secondary'),
  ('burpee', 'delt_front', 'secondary'),
  ('burpee_broad_jump', 'quads', 'primary'),
  ('burpee_broad_jump', 'glutes', 'primary'),
  ('burpee_broad_jump', 'chest', 'primary'),
  ('burpee_broad_jump', 'core', 'secondary'),
  ('burpee_broad_jump', 'calves', 'secondary'),
  ('box_jump', 'quads', 'primary'),
  ('box_jump', 'glutes', 'primary'),
  ('box_jump', 'calves', 'secondary'),
  ('box_jump_over', 'quads', 'primary'),
  ('box_jump_over', 'glutes', 'primary'),
  ('box_jump_over', 'calves', 'secondary'),
  ('sled_push', 'quads', 'primary'),
  ('sled_push', 'glutes', 'primary'),
  ('sled_push', 'calves', 'secondary'),
  ('sled_push', 'core', 'secondary'),
  ('sled_push', 'chest', 'secondary'),
  ('sled_pull', 'upper_back', 'primary'),
  ('sled_pull', 'lats', 'primary'),
  ('sled_pull', 'hamstrings', 'primary'),
  ('sled_pull', 'biceps', 'secondary'),
  ('sled_pull', 'forearms', 'secondary'),
  ('sled_pull', 'glutes', 'secondary'),
  ('farmers_carry', 'forearms', 'primary'),
  ('farmers_carry', 'upper_back', 'primary'),
  ('farmers_carry', 'core', 'secondary'),
  ('farmers_carry', 'glutes', 'secondary'),
  ('sandbag_lunge', 'quads', 'primary'),
  ('sandbag_lunge', 'glutes', 'primary'),
  ('sandbag_lunge', 'core', 'secondary'),
  ('sandbag_lunge', 'upper_back', 'secondary'),
  ('med_ball_situp_throw', 'core', 'primary'),
  ('med_ball_situp_throw', 'delt_front', 'secondary'),
  ('med_ball_situp_throw', 'chest', 'secondary'),
  ('dead_ball_over', 'glutes', 'primary'),
  ('dead_ball_over', 'hamstrings', 'primary'),
  ('dead_ball_over', 'lower_back', 'primary'),
  ('dead_ball_over', 'upper_back', 'secondary'),
  ('dead_ball_over', 'core', 'secondary'),
  ('skierg', 'lats', 'primary'),
  ('skierg', 'triceps', 'primary'),
  ('skierg', 'core', 'secondary'),
  ('skierg', 'delt_front', 'secondary'),
  ('row_erg', 'lats', 'primary'),
  ('row_erg', 'quads', 'primary'),
  ('row_erg', 'upper_back', 'primary'),
  ('row_erg', 'hamstrings', 'secondary'),
  ('row_erg', 'glutes', 'secondary'),
  ('row_erg', 'biceps', 'secondary'),
  ('air_bike', 'quads', 'primary'),
  ('air_bike', 'hamstrings', 'secondary'),
  ('air_bike', 'glutes', 'secondary'),
  ('air_bike', 'delt_front', 'secondary'),
  ('double_unders', 'calves', 'primary'),
  ('double_unders', 'delt_side', 'secondary'),
  ('double_unders', 'forearms', 'secondary')
on conflict (exercise_id, muscle_id) do update set role = excluded.role;
